package com.gp.brute.domain;

// Generated 11 déc. 2014 16:25:59 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tableferier generated by hbm2java
 */
@Entity
@Table(name = "tableferier", catalog = "gp")
public class Tableferier implements java.io.Serializable {

	private Integer tableferierId;
	private Ferier ferier;
	private Date jour;

	public Tableferier() {
	}

	public Tableferier(Ferier ferier, Date jour) {
		this.ferier = ferier;
		this.jour = jour;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "tableferierID", unique = true, nullable = false)
	public Integer getTableferierId() {
		return this.tableferierId;
	}

	public void setTableferierId(Integer tableferierId) {
		this.tableferierId = tableferierId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ferier", nullable = false)
	public Ferier getFerier() {
		return this.ferier;
	}

	public void setFerier(Ferier ferier) {
		this.ferier = ferier;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "jour", nullable = false, length = 10)
	public Date getJour() {
		return this.jour;
	}

	public void setJour(Date jour) {
		this.jour = jour;
	}

}
