package com.gp.domain;

// Generated 20 nov. 2014 13:37:48 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.outils.gp.Tool;

/**
 * Commission generated by hbm2java
 */
@Entity
@Table(name = "commission", catalog = "gp")
public class Commission implements java.io.Serializable {

	private Integer commissionId;
	private Exercice exercice;
	private Salarie salarie;
	private float montant;
	private String motif;
	private int mois;
	private Date date;

	public Commission() {
	}

	public Commission(Exercice exercice, Salarie salarie, float montant,
			String motif, int mois, Date date) {
		this.exercice = exercice;
		this.salarie = salarie;
		this.montant = montant;
		this.motif = motif;
		this.mois = mois;
		this.date = date;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "commissionId", unique = true, nullable = false)
	public Integer getCommissionId() {
		return this.commissionId;
	}

	public void setCommissionId(Integer commissionId) {
		this.commissionId = commissionId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "exercice", nullable = false)
	public Exercice getExercice() {
		return this.exercice;
	}

	public void setExercice(Exercice exercice) {
		this.exercice = exercice;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "salarie", nullable = false)
	public Salarie getSalarie() {
		return this.salarie;
	}

	public void setSalarie(Salarie salarie) {
		this.salarie = salarie;
	}

	@Column(name = "montant", nullable = false, precision = 12, scale = 0)
	public float getMontant() {
		return this.montant;
	}

	public void setMontant(float montant) {
		this.montant = montant;
	}

	@Column(name = "motif", nullable = false, length = 65535)
	public String getMotif() {
		return this.motif;
	}

	public void setMotif(String motif) {
		this.motif = motif;
	}

	@Column(name = "mois", nullable = false)
	public int getMois() {
		return this.mois;
	}

	public void setMois(int mois) {
		this.mois = mois;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date", nullable = false, length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	/*
	 * Mes fonctions
	 */
	
	@Override
	public String toString() {
		// TODO Auto-generated method stub
		return "Commission \nMontant : "+this.montant+"\nSalarie : "+this.salarie+"\nExerice : "+this.exercice+"\nCommissions pour le mois :"+this.mois+"\nEnregistré le :"+this.date;
	}
	public String mois(){
		return Tool.mois(this.mois);
	}
}
