package com.gp.domain;

// Generated 10 nov. 2014 19:05:50 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Message generated by hbm2java
 */
@Entity
@Table(name = "message", catalog = "gp")
public class Message implements java.io.Serializable {

	private Integer messageId;
	private Utilisateur utilisateurByDestinataire;
	private Utilisateur utilisateurByEmetteur;
	private String message;
	private Date date;
	private boolean lu;
	private String objet;
	private boolean propbareme;
	private String description;

	public Message() {
	}

	public Message(Utilisateur utilisateurByDestinataire,
			Utilisateur utilisateurByEmetteur, String message, Date date,
			boolean lu, String objet, boolean propbareme) {
		this.utilisateurByDestinataire = utilisateurByDestinataire;
		this.utilisateurByEmetteur = utilisateurByEmetteur;
		this.message = message;
		this.date = date;
		this.lu = lu;
		this.objet = objet;
		this.propbareme = propbareme;
	}

	public Message(Utilisateur utilisateurByDestinataire,
			Utilisateur utilisateurByEmetteur, String message, Date date,
			boolean lu, String objet, boolean propbareme, String description) {
		this.utilisateurByDestinataire = utilisateurByDestinataire;
		this.utilisateurByEmetteur = utilisateurByEmetteur;
		this.message = message;
		this.date = date;
		this.lu = lu;
		this.objet = objet;
		this.propbareme = propbareme;
		this.description = description;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "messageID", unique = true, nullable = false)
	public Integer getMessageId() {
		return this.messageId;
	}

	public void setMessageId(Integer messageId) {
		this.messageId = messageId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "destinataire", nullable = false)
	public Utilisateur getUtilisateurByDestinataire() {
		return this.utilisateurByDestinataire;
	}

	public void setUtilisateurByDestinataire(
			Utilisateur utilisateurByDestinataire) {
		this.utilisateurByDestinataire = utilisateurByDestinataire;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "emetteur", nullable = false)
	public Utilisateur getUtilisateurByEmetteur() {
		return this.utilisateurByEmetteur;
	}

	public void setUtilisateurByEmetteur(Utilisateur utilisateurByEmetteur) {
		this.utilisateurByEmetteur = utilisateurByEmetteur;
	}

	@Column(name = "message", nullable = false, length = 65535)
	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date", nullable = false, length = 19)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "lu", nullable = false)
	public boolean isLu() {
		return this.lu;
	}

	public void setLu(boolean lu) {
		this.lu = lu;
	}

	@Column(name = "objet", nullable = false, length = 250)
	public String getObjet() {
		return this.objet;
	}

	public void setObjet(String objet) {
		this.objet = objet;
	}

	@Column(name = "propbareme", nullable = false)
	public boolean isPropbareme() {
		return this.propbareme;
	}

	public void setPropbareme(boolean propbareme) {
		this.propbareme = propbareme;
	}

	@Column(name = "description", length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}
	/*
	 * Mes fonctions
	 */
	@Override
	public String toString() {
		// TODO Auto-generated method stub
		return "Message :\n Send by "+this.utilisateurByEmetteur.getLogin()+"\nReceiver : "+
				this.utilisateurByDestinataire.getLogin()+"\nObject :"+this.objet+"\nContent : "+
		this.message+"\n Is  proposition : "+this.propbareme+"\nDescription : "+this.description+"\nSend the :"+
				this.date;
	}

}
