package com.gp.domain;

// Generated 24 oct. 2014 14:38:22 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Message generated by hbm2java
 */
@Entity
@Table(name = "message", catalog = "gp")
public class Message implements java.io.Serializable {

	private Integer messageId;
	private Utilisateur utilisateurByDestinataire;
	private Utilisateur utilisateurByEmetteur;
	private String message;
	private int date;
	private boolean lu;

	public Message() {
	}

	public Message(Utilisateur utilisateurByDestinataire,
			Utilisateur utilisateurByEmetteur, String message, int date,
			boolean lu) {
		this.utilisateurByDestinataire = utilisateurByDestinataire;
		this.utilisateurByEmetteur = utilisateurByEmetteur;
		this.message = message;
		this.date = date;
		this.lu = lu;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "messageID", unique = true, nullable = false)
	public Integer getMessageId() {
		return this.messageId;
	}

	public void setMessageId(Integer messageId) {
		this.messageId = messageId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "destinataire", nullable = false)
	public Utilisateur getUtilisateurByDestinataire() {
		return this.utilisateurByDestinataire;
	}

	public void setUtilisateurByDestinataire(
			Utilisateur utilisateurByDestinataire) {
		this.utilisateurByDestinataire = utilisateurByDestinataire;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "emetteur", nullable = false)
	public Utilisateur getUtilisateurByEmetteur() {
		return this.utilisateurByEmetteur;
	}

	public void setUtilisateurByEmetteur(Utilisateur utilisateurByEmetteur) {
		this.utilisateurByEmetteur = utilisateurByEmetteur;
	}

	@Column(name = "message", nullable = false, length = 65535)
	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	@Column(name = "date", nullable = false)
	public int getDate() {
		return this.date;
	}

	public void setDate(int date) {
		this.date = date;
	}

	@Column(name = "lu", nullable = false)
	public boolean isLu() {
		return this.lu;
	}

	public void setLu(boolean lu) {
		this.lu = lu;
	}

}
