package com.gp.domain;

// Generated 10 déc. 2014 16:46:00 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Message generated by hbm2java
 */
@Entity
@Table(name = "message", catalog = "gp")
public class Message implements java.io.Serializable {

	private Integer messageId;
	private Utilisateur utilisateurByDestinataire;
	private Utilisateur utilisateurByEmetteur;
	private String message;
	private Date dateenvoi;
	private boolean lu;
	private String objet;
	private Boolean fichier;
	private String nomfichier;
	private String nomdossier;

	public Message() {
	}

	public Message(Utilisateur utilisateurByDestinataire,
			Utilisateur utilisateurByEmetteur, String message, Date dateenvoi,
			boolean lu, String objet) {
		this.utilisateurByDestinataire = utilisateurByDestinataire;
		this.utilisateurByEmetteur = utilisateurByEmetteur;
		this.message = message;
		this.dateenvoi = dateenvoi;
		this.lu = lu;
		this.objet = objet;
	}

	public Message(Utilisateur utilisateurByDestinataire,
			Utilisateur utilisateurByEmetteur, String message, Date dateenvoi,
			boolean lu, String objet, Boolean fichier, String nomfichier,
			String nomdossier) {
		this.utilisateurByDestinataire = utilisateurByDestinataire;
		this.utilisateurByEmetteur = utilisateurByEmetteur;
		this.message = message;
		this.dateenvoi = dateenvoi;
		this.lu = lu;
		this.objet = objet;
		this.fichier = fichier;
		this.nomfichier = nomfichier;
		this.nomdossier = nomdossier;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "messageID", unique = true, nullable = false)
	public Integer getMessageId() {
		return this.messageId;
	}

	public void setMessageId(Integer messageId) {
		this.messageId = messageId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "destinataire", nullable = false)
	public Utilisateur getUtilisateurByDestinataire() {
		return this.utilisateurByDestinataire;
	}

	public void setUtilisateurByDestinataire(
			Utilisateur utilisateurByDestinataire) {
		this.utilisateurByDestinataire = utilisateurByDestinataire;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "emetteur", nullable = false)
	public Utilisateur getUtilisateurByEmetteur() {
		return this.utilisateurByEmetteur;
	}

	public void setUtilisateurByEmetteur(Utilisateur utilisateurByEmetteur) {
		this.utilisateurByEmetteur = utilisateurByEmetteur;
	}

	@Column(name = "message", nullable = false, length = 65535)
	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateenvoi", nullable = false, length = 10)
	public Date getDateenvoi() {
		return this.dateenvoi;
	}

	public void setDateenvoi(Date dateenvoi) {
		this.dateenvoi = dateenvoi;
	}

	@Column(name = "lu", nullable = false)
	public boolean isLu() {
		return this.lu;
	}

	public void setLu(boolean lu) {
		this.lu = lu;
	}

	@Column(name = "objet", nullable = false, length = 250)
	public String getObjet() {
		return this.objet;
	}

	public void setObjet(String objet) {
		this.objet = objet;
	}

	@Column(name = "fichier")
	public Boolean getFichier() {
		return this.fichier;
	}

	public void setFichier(Boolean fichier) {
		this.fichier = fichier;
	}

	@Column(name = "nomfichier")
	public String getNomfichier() {
		return this.nomfichier;
	}

	public void setNomfichier(String nomfichier) {
		this.nomfichier = nomfichier;
	}

	@Column(name = "nomdossier")
	public String getNomdossier() {
		return this.nomdossier;
	}

	public void setNomdossier(String nomdossier) {
		this.nomdossier = nomdossier;
	}
	/*
	 * Mes fonctions
	 */
	@Override
	public String toString() {
		// TODO Auto-generated method stub
		return "Message de "+this.utilisateurByEmetteur.getLogin()+" pour "+this.utilisateurByDestinataire.getLogin()+
				"\nContenu : "+this.message+"\nObjet : "+this.objet+
				"\nAttach fichier : "+this.fichier+
				"\nNom du fichier : "+this.nomfichier+
				"\nNom du dossier : "+this.nomdossier+
				"\nMessage envoyé le "+this.dateenvoi;
	}
	public String inter(String rubrique){
		if(rubrique.equals("message-envoyes"))
			return this.utilisateurByDestinataire.nom();
		return this.utilisateurByEmetteur.nom();
	}
	public String lien(){
		String lien  = "/documents/"+this.utilisateurByEmetteur.getLogin()+"/Fichier/"+this.nomdossier+"/"+this.nomfichier;
		if(this.utilisateurByEmetteur.getLogin().equals("admin")){
			lien = "/documents/"+this.utilisateurByDestinataire.getLogin()+"/Fichier/"+this.nomdossier+"/"+this.nomfichier;
		}
		return lien;
	}

}
