package com.gp.domain;

// Generated 20 nov. 2014 22:21:26 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Parametre generated by hbm2java
 */
@Entity
@Table(name = "parametre", catalog = "gp")
public class Parametre implements java.io.Serializable {

	private Integer parametreId;
	private Integer alertefinperiodeessai;
	private String unite;
	private Integer nbreunite;
	private Set<Societe> societes = new HashSet<Societe>(0);

	public Parametre() {
	}

	public Parametre(String unite, Integer nbreunite) {
		this.unite = unite;
		this.nbreunite = nbreunite;
	}

	public Parametre(Integer alertefinperiodeessai, String unite,
			Integer nbreunite, Set<Societe> societes) {
		this.alertefinperiodeessai = alertefinperiodeessai;
		this.unite = unite;
		this.nbreunite = nbreunite;
		this.societes = societes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "parametreId", unique = true, nullable = false)
	public Integer getParametreId() {
		return this.parametreId;
	}

	public void setParametreId(Integer parametreId) {
		this.parametreId = parametreId;
	}

	@Column(name = "alertefinperiodeessai")
	public Integer getAlertefinperiodeessai() {
		return this.alertefinperiodeessai;
	}

	public void setAlertefinperiodeessai(Integer alertefinperiodeessai) {
		this.alertefinperiodeessai = alertefinperiodeessai;
	}

	@Column(name = "unite", nullable = true, length = 100)
	public String getUnite() {
		return this.unite;
	}

	public void setUnite(String unite) {
		this.unite = unite;
	}

	@Column(name = "nbreunite", nullable = true)
	public Integer getNbreunite() {
		return this.nbreunite;
	}

	public void setNbreunite(Integer nbreunite) {
		this.nbreunite = nbreunite;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "parametre")
	public Set<Societe> getSocietes() {
		return this.societes;
	}

	public void setSocietes(Set<Societe> societes) {
		this.societes = societes;
	}

}
