package com.gp.domain;

// Generated 20 nov. 2014 14:23:10 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.outils.gp.Tool;

/**
 * Primedate generated by hbm2java
 */
@Entity
@Table(name = "primedate", catalog = "gp")
public class Primedate implements java.io.Serializable {

	private Integer primedateId;
	private Prime prime;
	private int mois;

	public Primedate() {
	}

	public Primedate(Prime prime, int mois) {
		this.prime = prime;
		this.mois = mois;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "primedateID", unique = true, nullable = false)
	public Integer getPrimedateId() {
		return this.primedateId;
	}

	public void setPrimedateId(Integer primedateId) {
		this.primedateId = primedateId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "prime", nullable = false)
	public Prime getPrime() {
		return this.prime;
	}

	public void setPrime(Prime prime) {
		this.prime = prime;
	}

	@Column(name = "mois", nullable = false)
	public int getMois() {
		return this.mois;
	}

	public void setMois(int mois) {
		this.mois = mois;
	}
	/*
	 * Mes fonctions
	 */
	
	@Override
	public String toString() {
		// TODO Auto-generated method stub
		return Tool.mois(this.mois)+"\n";
	}
	public String mois(){
		return Tool.mois(this.mois);
	}

}
