package com.gp.domain;

// Generated 24 oct. 2014 14:48:38 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.joda.time.DateTime;

/**
 * Societebareme generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "societebareme", catalog = "gp")
public class Societebareme implements java.io.Serializable {

	private Integer societebaremeId;
	private Societe societe;
	private Bareme bareme;
	private long date;

	public Societebareme() {
		this.date = new DateTime().getMillis();
	}

	public Societebareme(Societe societe, Bareme bareme, int date) {
		this.societe = societe;
		this.bareme = bareme;
		this.date = date;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "societebaremeID", unique = true, nullable = false)
	public Integer getSocietebaremeId() {
		return this.societebaremeId;
	}

	public void setSocietebaremeId(Integer societebaremeId) {
		this.societebaremeId = societebaremeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "societeID", nullable = false)
	public Societe getSociete() {
		return this.societe;
	}

	public void setSociete(Societe societe) {
		this.societe = societe;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "baremeID", nullable = false)
	public Bareme getBareme() {
		return this.bareme;
	}

	public void setBareme(Bareme bareme) {
		this.bareme = bareme;
	}

	@Column(name = "date", nullable = false)
	public long getDate() {
		return this.date;
	}

	public void setDate(long date) {
		this.date = date;
	}

}
