package com.outils.gp;

// Generated 3 déc. 2014 22:27:01 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Jourferier generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "jourferier", catalog = "gp")
public class Jourferier implements java.io.Serializable {

	private Integer jourferierId;
	private Ferier ferier;
	private Date date;

	public Jourferier() {
	}

	public Jourferier(Ferier ferier, Date date) {
		this.ferier = ferier;
		this.date = date;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "jourferierID", unique = true, nullable = false)
	public Integer getJourferierId() {
		return this.jourferierId;
	}

	public void setJourferierId(Integer jourferierId) {
		this.jourferierId = jourferierId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tableferier", nullable = false)
	public Ferier getFerier() {
		return this.ferier;
	}

	public void setFerier(Ferier ferier) {
		this.ferier = ferier;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date", nullable = false, length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

}
