package com.gp.domain.base.brute;

// Generated 9 déc. 2014 16:21:18 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Primesalarie generated by hbm2java
 */
@Entity
@Table(name = "primesalarie", catalog = "gp")
public class Primesalarie implements java.io.Serializable {

	private Integer primesalarieId;
	private Exercice exercice;
	private Prime prime;
	private Salarie salarie;
	private Date date;

	public Primesalarie() {
	}

	public Primesalarie(Exercice exercice, Prime prime, Salarie salarie,
			Date date) {
		this.exercice = exercice;
		this.prime = prime;
		this.salarie = salarie;
		this.date = date;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "primesalarieID", unique = true, nullable = false)
	public Integer getPrimesalarieId() {
		return this.primesalarieId;
	}

	public void setPrimesalarieId(Integer primesalarieId) {
		this.primesalarieId = primesalarieId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "exercice", nullable = false)
	public Exercice getExercice() {
		return this.exercice;
	}

	public void setExercice(Exercice exercice) {
		this.exercice = exercice;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "prime", nullable = false)
	public Prime getPrime() {
		return this.prime;
	}

	public void setPrime(Prime prime) {
		this.prime = prime;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "salarie", nullable = false)
	public Salarie getSalarie() {
		return this.salarie;
	}

	public void setSalarie(Salarie salarie) {
		this.salarie = salarie;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date", nullable = false, length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

}
