package com.gp.domain.base.brute;

// Generated 9 déc. 2014 16:21:18 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Salaire generated by hbm2java
 */
@Entity
@Table(name = "salaire", catalog = "gp")
public class Salaire implements java.io.Serializable {

	private Integer salaireId;
	private Exercice exercice;
	private Salarie salarie;
	private float montant;
	private Date date;
	private int mois;

	public Salaire() {
	}

	public Salaire(Exercice exercice, Salarie salarie, float montant,
			Date date, int mois) {
		this.exercice = exercice;
		this.salarie = salarie;
		this.montant = montant;
		this.date = date;
		this.mois = mois;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "salaireId", unique = true, nullable = false)
	public Integer getSalaireId() {
		return this.salaireId;
	}

	public void setSalaireId(Integer salaireId) {
		this.salaireId = salaireId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "exercice", nullable = false)
	public Exercice getExercice() {
		return this.exercice;
	}

	public void setExercice(Exercice exercice) {
		this.exercice = exercice;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "salarie", nullable = false)
	public Salarie getSalarie() {
		return this.salarie;
	}

	public void setSalarie(Salarie salarie) {
		this.salarie = salarie;
	}

	@Column(name = "montant", nullable = false, precision = 12, scale = 0)
	public float getMontant() {
		return this.montant;
	}

	public void setMontant(float montant) {
		this.montant = montant;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date", nullable = false, length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "mois", nullable = false)
	public int getMois() {
		return this.mois;
	}

	public void setMois(int mois) {
		this.mois = mois;
	}

}
