package com.gp.domain.base.brute;

// Generated 9 déc. 2014 16:21:18 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Salariebareme generated by hbm2java
 */
@Entity
@Table(name = "salariebareme", catalog = "gp")
public class Salariebareme implements java.io.Serializable {

	private Integer salariebaremeId;
	private Societebareme societebareme;
	private Salarie salarie;
	private String salarieId;

	public Salariebareme() {
	}

	public Salariebareme(Societebareme societebareme, Salarie salarie,
			String salarieId) {
		this.societebareme = societebareme;
		this.salarie = salarie;
		this.salarieId = salarieId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "salariebaremeID", unique = true, nullable = false)
	public Integer getSalariebaremeId() {
		return this.salariebaremeId;
	}

	public void setSalariebaremeId(Integer salariebaremeId) {
		this.salariebaremeId = salariebaremeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bareme", nullable = false)
	public Societebareme getSocietebareme() {
		return this.societebareme;
	}

	public void setSocietebareme(Societebareme societebareme) {
		this.societebareme = societebareme;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "salarie", nullable = false)
	public Salarie getSalarie() {
		return this.salarie;
	}

	public void setSalarie(Salarie salarie) {
		this.salarie = salarie;
	}

	@Column(name = "salarieID", nullable = false)
	public String getSalarieId() {
		return this.salarieId;
	}

	public void setSalarieId(String salarieId) {
		this.salarieId = salarieId;
	}

}
