package com.gp.domain.base.brute;

// Generated 9 déc. 2014 16:21:18 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Salarie generated by hbm2java
 */
@Entity
@Table(name = "salarie", catalog = "gp")
public class Salarie implements java.io.Serializable {

	private Integer salarieId;
	private Contrat contrat;
	private Etatcivile etatcivile;
	private Paie paie;
	private Poste poste;
	private Coordonneebancaire coordonneebancaire;
	private Immatriculation immatriculation;
	private Societe societe;
	private String dossier;
	private String image;
	private int nbrejour;
	private Boolean active;
	private Set<Avance> avances = new HashSet<Avance>(0);
	private Set<Commission> commissions = new HashSet<Commission>(0);
	private Set<Conge> conges = new HashSet<Conge>(0);
	private Set<Salaire> salaires = new HashSet<Salaire>(0);
	private Set<Salariebareme> salariebaremes = new HashSet<Salariebareme>(0);
	private Set<Primesalarie> primesalaries = new HashSet<Primesalarie>(0);
	private Set<Document> documents = new HashSet<Document>(0);

	public Salarie() {
	}

	public Salarie(String dossier, int nbrejour) {
		this.dossier = dossier;
		this.nbrejour = nbrejour;
	}

	public Salarie(Contrat contrat, Etatcivile etatcivile, Paie paie,
			Poste poste, Coordonneebancaire coordonneebancaire,
			Immatriculation immatriculation, Societe societe, String dossier,
			String image, int nbrejour, Boolean active, Set<Avance> avances,
			Set<Commission> commissions, Set<Conge> conges,
			Set<Salaire> salaires, Set<Salariebareme> salariebaremes,
			Set<Primesalarie> primesalaries, Set<Document> documents) {
		this.contrat = contrat;
		this.etatcivile = etatcivile;
		this.paie = paie;
		this.poste = poste;
		this.coordonneebancaire = coordonneebancaire;
		this.immatriculation = immatriculation;
		this.societe = societe;
		this.dossier = dossier;
		this.image = image;
		this.nbrejour = nbrejour;
		this.active = active;
		this.avances = avances;
		this.commissions = commissions;
		this.conges = conges;
		this.salaires = salaires;
		this.salariebaremes = salariebaremes;
		this.primesalaries = primesalaries;
		this.documents = documents;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "salarieID", unique = true, nullable = false)
	public Integer getSalarieId() {
		return this.salarieId;
	}

	public void setSalarieId(Integer salarieId) {
		this.salarieId = salarieId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "contratID")
	public Contrat getContrat() {
		return this.contrat;
	}

	public void setContrat(Contrat contrat) {
		this.contrat = contrat;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "etatcivileID")
	public Etatcivile getEtatcivile() {
		return this.etatcivile;
	}

	public void setEtatcivile(Etatcivile etatcivile) {
		this.etatcivile = etatcivile;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "paieID")
	public Paie getPaie() {
		return this.paie;
	}

	public void setPaie(Paie paie) {
		this.paie = paie;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "posteID")
	public Poste getPoste() {
		return this.poste;
	}

	public void setPoste(Poste poste) {
		this.poste = poste;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "coordoneebancaireID")
	public Coordonneebancaire getCoordonneebancaire() {
		return this.coordonneebancaire;
	}

	public void setCoordonneebancaire(Coordonneebancaire coordonneebancaire) {
		this.coordonneebancaire = coordonneebancaire;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "immatriculationID")
	public Immatriculation getImmatriculation() {
		return this.immatriculation;
	}

	public void setImmatriculation(Immatriculation immatriculation) {
		this.immatriculation = immatriculation;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "societeID")
	public Societe getSociete() {
		return this.societe;
	}

	public void setSociete(Societe societe) {
		this.societe = societe;
	}

	@Column(name = "dossier", nullable = false)
	public String getDossier() {
		return this.dossier;
	}

	public void setDossier(String dossier) {
		this.dossier = dossier;
	}

	@Column(name = "image")
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Column(name = "nbrejour", nullable = false)
	public int getNbrejour() {
		return this.nbrejour;
	}

	public void setNbrejour(int nbrejour) {
		this.nbrejour = nbrejour;
	}

	@Column(name = "active")
	public Boolean getActive() {
		return this.active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "salarie")
	public Set<Avance> getAvances() {
		return this.avances;
	}

	public void setAvances(Set<Avance> avances) {
		this.avances = avances;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "salarie")
	public Set<Commission> getCommissions() {
		return this.commissions;
	}

	public void setCommissions(Set<Commission> commissions) {
		this.commissions = commissions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "salarie")
	public Set<Conge> getConges() {
		return this.conges;
	}

	public void setConges(Set<Conge> conges) {
		this.conges = conges;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "salarie")
	public Set<Salaire> getSalaires() {
		return this.salaires;
	}

	public void setSalaires(Set<Salaire> salaires) {
		this.salaires = salaires;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "salarie")
	public Set<Salariebareme> getSalariebaremes() {
		return this.salariebaremes;
	}

	public void setSalariebaremes(Set<Salariebareme> salariebaremes) {
		this.salariebaremes = salariebaremes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "salarie")
	public Set<Primesalarie> getPrimesalaries() {
		return this.primesalaries;
	}

	public void setPrimesalaries(Set<Primesalarie> primesalaries) {
		this.primesalaries = primesalaries;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "salarie")
	public Set<Document> getDocuments() {
		return this.documents;
	}

	public void setDocuments(Set<Document> documents) {
		this.documents = documents;
	}

}
