package com.gp.domainnews;

// Generated 20 nov. 2014 15:33:35 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.gp.domain.Primedate;

/**
 * Prime generated by hbm2java
 */
@Entity
@Table(name = "prime", catalog = "gp")
public class Prime implements java.io.Serializable {

	private Integer primeId;
	private Societe societe;
	private float montant;
	private String motif;
	private String type;
	private String nom;
	private Set<Primedate> primedates = new HashSet<Primedate>(0);
	private Set<Primesalarie> primesalaries = new HashSet<Primesalarie>(0);

	public Prime() {
	}

	public Prime(float montant, String motif, String type, String nom) {
		this.montant = montant;
		this.motif = motif;
		this.type = type;
		this.nom = nom;
	}

	public Prime(Societe societe, float montant, String motif, String type,
			String nom, Set<Primedate> primedates,
			Set<Primesalarie> primesalaries) {
		this.societe = societe;
		this.montant = montant;
		this.motif = motif;
		this.type = type;
		this.nom = nom;
		this.primedates = primedates;
		this.primesalaries = primesalaries;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "primeID", unique = true, nullable = false)
	public Integer getPrimeId() {
		return this.primeId;
	}

	public void setPrimeId(Integer primeId) {
		this.primeId = primeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "societe")
	public Societe getSociete() {
		return this.societe;
	}

	public void setSociete(Societe societe) {
		this.societe = societe;
	}

	@Column(name = "montant", nullable = false, precision = 12, scale = 0)
	public float getMontant() {
		return this.montant;
	}

	public void setMontant(float montant) {
		this.montant = montant;
	}

	@Column(name = "motif", nullable = false, length = 65535)
	public String getMotif() {
		return this.motif;
	}

	public void setMotif(String motif) {
		this.motif = motif;
	}

	@Column(name = "type", nullable = false, length = 100)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "nom", nullable = false, length = 250)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "prime")
	public Set<Primedate> getPrimedates() {
		return this.primedates;
	}

	public void setPrimedates(Set<Primedate> primedates) {
		this.primedates = primedates;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "prime")
	public Set<Primesalarie> getPrimesalaries() {
		return this.primesalaries;
	}

	public void setPrimesalaries(Set<Primesalarie> primesalaries) {
		this.primesalaries = primesalaries;
	}
	
	/*
	 * Mes fonctions
	 */
	@Override
	public String toString() {
		// TODO Auto-generated method stub
		return "Prime : "+this.nom+
				"\nMontant : "+this.montant+
				"\nMotif : "+this.motif+
				"\nType : "+this.type+
				"\nLes mois : "+this.primedates;
	}
	public String mois(){
		String mois ="";
		for(Primedate pd:this.primedates)
			mois += pd.mois()+",";
		
		if(mois.length() > 0)
			mois = mois.substring(0, mois.length()-1);
		return mois;
	}

}
