package com.gp.domainnews;

// Generated 24 oct. 2014 14:58:33 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Salariebareme generated by hbm2java
 */
@Entity
@Table(name = "salariebareme", catalog = "gp")
public class Salariebareme implements java.io.Serializable {

	private Integer salariebaremeId;
	private Bareme bareme;
	private Salarie salarie;
	private String salarieId;
	private int date;

	public Salariebareme() {
	}

	public Salariebareme(Bareme bareme, Salarie salarie, String salarieId,
			int date) {
		this.bareme = bareme;
		this.salarie = salarie;
		this.salarieId = salarieId;
		this.date = date;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "salariebaremeID", unique = true, nullable = false)
	public Integer getSalariebaremeId() {
		return this.salariebaremeId;
	}

	public void setSalariebaremeId(Integer salariebaremeId) {
		this.salariebaremeId = salariebaremeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bareme", nullable = false)
	public Bareme getBareme() {
		return this.bareme;
	}

	public void setBareme(Bareme bareme) {
		this.bareme = bareme;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "salarie", nullable = false)
	public Salarie getSalarie() {
		return this.salarie;
	}

	public void setSalarie(Salarie salarie) {
		this.salarie = salarie;
	}

	@Column(name = "salarieID", nullable = false)
	public String getSalarieId() {
		return this.salarieId;
	}

	public void setSalarieId(String salarieId) {
		this.salarieId = salarieId;
	}

	@Column(name = "date", nullable = false)
	public int getDate() {
		return this.date;
	}

	public void setDate(int date) {
		this.date = date;
	}

}
